### ISSUE TITLE
Import Facility list from GIS

### ISSUE THREAD

**Issue by jofomah** [eHealthAfrica/direct-delivery-dashboard#113]

**Comment by jofomah** [comment]
This can be in form of CSV upload or Web UI but MOST IMPORTANTLY should match location level data model

**Comment by janetbutts** [comment]
@tlvince, @freefony has pulled this data before and will be able to give you the links to the web service/api from GIS.  @freefony, can you provide the relevant links?

**Comment by freefony** [comment]
@janetbutts , @tlvince, i pulled data via Kano Connect API so i don't have the links. It's Jacub who has worked directly with GIS APIs as i know.

**Comment by janetbutts** [comment]
@freefony , ah that's right. thanks.

**Comment by tlvince** [comment]
Could I get some clarification here?
- We currently don't have any facility docs (in the `deliveries` DB). Is this what is meant?
- Is this a one-time operation or should it be a feature on https://stage-dd.ehealth.org.ng?
  - If the latter, where should it live? Under the configurations tab?
  - Once imported, how should it be displayed? Like the products configuration? Will it need basic Create Read Update Delete (CRUD) for each record?
- What's the URL for the GIS API? Is it documented?
- What does the data to be imported look like? Is simply a list of strings? Or, which fields are pertinent?

**Comment by tlvince** [comment]
Feel free to assign back to me when ready.

**Comment by janetbutts** [comment]
2@grillazz , can you please share the GIS API with @tlvince ? @freefony & @musamusa , can you answer @tlvince 's questions about the format?

**Comment by tlvince** [comment]
API: http://data.ehealthafrica.org/dataset/health-facilities-working-data

**Comment by tlvince** [comment]
~~Working on this.~~
