### ISSUE TITLE
Handle user sessions properly

### ISSUE THREAD

**Issue by jofomah** [eHealthAfrica/direct-delivery-dashboard#15]

**Comment by jofomah** [comment]
Currently, if users session expires or timeout, it is not handle properly by the app. it should force a re-login or find away to recreate session behind the scene instead of :
Actions failing because the session has expired unless user refreshes the page before login page is shown.

**Comment by tlvince** [comment]
A couple of solutions to this:
- Tune CouchDB's cookie auth expiry time
- Enable CouchDB's persistent auth
- Wrap all CouchDB calls with something like [angular-eha.retriable](https://github.com/eHealthAfrica/angular-eha.retriable), which will make a request to `_session` on 401
- (Potentially) use angular-eha.couchdb-auth's [$http interceptor](https://github.com/eHealthAfrica/angular-eha.couchdb-auth/tree/c4f2939583084236ff09f3ecec96f7f64fdb6207#configuration)

**Comment by tlvince** [comment]
In Move (and others), we use retriable to [show a dialog box](http://docs.ehealthafrica.org/angular-eha.login-dialog/). This could potentially replace the login page.

**Comment by jofomah** [comment]
@tlvince i like the idea of using a dialog box i.e the approach we used for Move, will other also will use angular-eha.couchdb-auth's $http interceptor redirect to login page and prompt user to login???

**Comment by tlvince** [comment]
Yeah, though I doubt the `$http` interceptor will work as it intercepts Angular `$http` calls, whereas we're using PouchDB.

**Comment by jofomah** [comment]
Closing now because i can't reproduce, have been fixed by replacing custom auth service with auth service backed by angular-eha.couchdb-auth

**Comment by tlvince** [comment]
Here's a way to reproduce this:
1. Disable admin party
2. Set the security document on the `deliveries` DB, e.g.: admin names: `["admin"]`, member names `["gis"]`
3. In CouchDB configuration, reduce `couch_httpd_auth.timeout` to 10 (seconds, default: 600; 10 mins)
4. Login to the app as user: `gis`, pw: `gis`
5. Wait ten seconds
6. Browse to planning tab. "No delivery rounds found." and 401 errors in the console
