### ISSUE TITLE
Spurious user not found messages

### ISSUE THREAD

**Issue by tlvince** [eHealthAfrica/direct-delivery-dashboard#154]
`[Debug] User not found (vendor-7b73bd566d.js, line 21541, x4)` is logged on first boot. Related to angular-eha.couchdb-auth.

**Comment by Chima1707** [comment]
I did some debugging and i found out that , whenever getCurrentUser is called and their is no currentUser in context or inside localForage as a result of logout action or refresh just as the case of when you navigate to the dashboard at first, user not found message get logged by the internal angular $log service. I don't think this is a problem as  angular-eha.couchdb-auth module is behaving as expected. Remember each of the menu items  on the Navbar, has a directive eha-show-authenticated placed on it that also calls the getCurrentUser functions too internally.

**Comment by tlvince** [comment]
In that case, perhaps we should remove the log from https://github.com/eHealthAfrica/angular-eha.couchdb-auth itself?

**Comment by Chima1707** [comment]
couchdb:login:success also get logged too .May be we should remove it the next version of angular-eha.couchdb-auth, should i open an issue for that?

**Comment by tlvince** [comment]
Yeah sounds good. Maybe even better would be to make log levels configurable.

**Comment by Chima1707** [comment]
yea, may be something that can be configured in a provider in the config block on application startup

**Comment by tlvince** [comment]
+1

**Comment by tlvince** [comment]
We decided to go with `$logProvider.debugEnabled(false)` instead of modifying angular-eha.couchdb-auth
