### ISSUE TITLE
deliveryRoundService#getReport returning no results

### ISSUE THREAD

**Issue by tlvince** [eHealthAfrica/direct-delivery-dashboard#186]
KN-233-2015 exists on the (dev) DB, however, the report-by-round view is returning no results.

**Comment by jofomah** [comment]
Was due to unknown changes to the view, fixed!

**Comment by tlvince** [comment]
Was that fixed in 6a5d774803e1e1ed545daed87de9466c73fcc083? I'm still seeing empty results on https://dev-dd.ehealth.org.ng for KN-233-2015.
