### ISSUE TITLE
Round Progress start date bug

### ISSUE THREAD

**Issue by jofomah** [eHealthAfrica/direct-delivery-dashboard#281]

**Comment by jofomah** [comment]
Round Progress bar always start from dates before Delivery Round start date, find attached a copy of the screenshot:
https://drive.google.com/a/ehealthnigeria.org/file/d/0B3JqadXCUEcVdHhIRVNGVHMySDg/view?usp=sharing

KN-30-2015 : for instance should start from first week of october, 2015 to last date of October, 2015.

Possible cause: Bug in views, query end key format, or corrupt test data.

**Comment by freefony** [comment]
this looks more like a data issue
