### ISSUE TITLE
KPI workflow flaw

### ISSUE THREAD

**Issue by jofomah** [eHealthAfrica/direct-delivery-dashboard#327]
KPI documents need to be in existence before the mobile part can work with it, currently there is no create way on the KPI to create KPI's, deliveries without KPI document are filled in using KPI template, issues with this:
- User have to manually save kpi docs for deliveries
- User need to update kpi date field every time the corresponding delivery doc is rescheduled.

Possible solutions:
- Every time, delivery doc is modified on the dashboard, fetch corresponding kpi document and update schedule date?  Though this will break easily if the change is made via the DB admin.
- Create new KPI from template, creates only KPI template, sync it to tablets, on tablet query for `kpi` document if it does not exist, create from the template. This will make sure only collected kpi documents exists on the db, changes to upcoming delivery dates won't required changes to corresponding kpi document. though we can still try to update kpi document if it exist just as a sanity check.

**Comment by DonkeyOatie** [comment]
@jofomah how likely is it that a change would be made in the DB admin interface?  The first solution seems like the easier but more fragile fix. Would it be sensible to go with the first solution for the Kano go-live date and then implement the more robust fix later? If so, are there any possible side effects to this approach and swapping the solution to the more robust option later?

**Comment by DonkeyOatie** [comment]
After discussion with @jofomah we decided we should implement solution 2.  This needs to be assigned and estimated.

**Comment by freefony** [comment]
@jofomah , @nkhumphreys so if we going with option 2, should this be a task on https://github.com/eHealthAfrica/direct-delivery instead ?

**Comment by jofomah** [comment]
Hey Femi,

Option two will involve syncing KPI template to the tablet and updating KPI
workflow on the device to check first if KPI already exist for given date,
hf and driver, else create from template.
