### ISSUE TITLE
planning: upload schedule doesn't work

### ISSUE THREAD

**Issue by janetbutts** [eHealthAfrica/direct-delivery-dashboard#333]
Doesn't upload or update.

**Comment by janetbutts** [comment]
@yusufscratch to check with dev team about the format of the CSV file to ensure that is not the issue. if the format is an issue, we can put in a example document to make it easier for the user

**Comment by freefony** [comment]
This works fine. The flow is, for a fresh round, import facilities ->export for routing -> upload schedule info. but there some issues with importing that ll create separate tickets for while this should be closed, i think.

**Comment by janetbutts** [comment]
@yusufscratch, qa this again using the proper method

**Comment by yusufumars** [comment]
QA the import facilities> export for rounting> upload schedule info and its a Pass.

**Comment by tlvince** [comment]
Taking that as confirmation this works. Please reopen if that's not the case.
