### ISSUE TITLE
Duplicated faulty CCE report

### ISSUE THREAD

**Issue by tlvince** [eHealthAfrica/direct-delivery-dashboard#360]
Is https://dev-dd.ehealth.org.ng/#/reports/facility is duplicated with https://dev-dd.ehealth.org.ng/#/facility/faulty? If so, which should be removed?

/cc @Chima1707, @Femi-ol

**Comment by Chima1707** [comment]
No, it is not a duplicate, one i meant to show all facilities while the other is meant to show faulty facilities

**Comment by tlvince** [comment]
OK.
