### ISSUE TITLE
report by each antigen pack, delivered and return by administrative level

### ISSUE THREAD

**Issue by janetbutts** [eHealthAfrica/direct-delivery-dashboard#69]
by zone
lga
ward
with a date range

**Comment by janetbutts** [comment]
@musamusa:
Add a label to the page indicating the name of the report
Create a tree system where people can choose reports by category (for when there are many more reports)

**Comment by janetbutts** [comment]
@musamusa , did the changes that adamu requested in the demo get updated on this?

**Comment by musamusa** [comment]
@janetbutts yes except the column header for 'On Hand Qty', didn't remember the recommended title. I'll add that in my next pull request

**Comment by janetbutts** [comment]
@musamusa 
the changes are as follows:
change the labels:
Parking to packing
expected qty to packed qty
on hand qty to stock at hand
also
reorder list:
use the google sheet to to determine the order
