### ISSUE TITLE
create login for accounting department for dashboard accounting report

### ISSUE THREAD

**Issue by janetbutts** [eHealthAfrica/direct-delivery-dashboard#7]

**Comment by hbj** [comment]
@tlvince We need a user with RW access to the `deliveries` and `_users` dbs on btoh staging and production. Can you please create them and add them to the 'Credentials' Google sheet?

**Comment by tlvince** [comment]
There's the `dd_admin`/`deliveries_admin` user for `deliveries`: https://docs.google.com/spreadsheets/d/1sCTmkiwxQJ9jsfL1Gy-IUetqRMEKmQkRf_D96o1qPhw/edit#gid=0

Re `_users`, do you have a fixed list of accounts that need creating?

**Comment by hbj** [comment]
@janetbutts can you please provide the account information?

@tlvince access to the `_users` db is also required by the new user management interface of the dd dashboard, so the person managing the users will need full access to it.

**Comment by janetbutts** [comment]
Sorry all, this slipped by me.  Here it is:
Managers who will access the dashboard:
[redacted]

Drivers who need access to the application:
[redacted]

**Comment by hbj** [comment]
Assigned to @tlvince because I don't have admin access to the databases.

**Comment by janetbutts** [comment]
Hi @tlvince, can you please assist?

**Comment by tlvince** [comment]
@janetbutts see @futuresandwich's reply to 'Fwd: Re: Dashboard':

> In my mind most eHealth products sharing the same CouchDB instance(s) is risky on a great many levels.
> I've discussed very briefly with Lutz and think we would schedule a dedicated instance for DD. 
> Copying Yioula to track the task. Tom / Jide what's the timeline / urgency?

So, we're waiting on a new CouchDB instance. @Charlie-Brown may know the timeline.

**Comment by janetbutts** [comment]
@charlie-brown, what would be the time-frame for the new instance?

**Comment by janetbutts** [comment]
@Charlie-Brown, can you please update the group about the timeframe that you can create the new instance? Thx

**Comment by janetbutts** [comment]
@futuresandwich , do you have any information on the creation of the new DD instance?

**Comment by janetbutts** [comment]
@jofomah , do we still need this task?
